---
- name: Déployer Flask Quote API
  hosts: webservers
  become: yes
  tasks:

    - name: Installer Docker
      yum:
        name: docker
        state: present

    - name: Démarrer et activer Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Ajouter l'utilisateur ec2-user au groupe docker
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Copier le code Flask depuis Jenkins vers l'EC2
      copy:
        src: /var/lib/jenkins/workspace/demo-flask-ansible/
        dest: /home/ec2-user/demo-flask-ansible/
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Construire l'image Docker
      community.docker.docker_image:
        source: build
        build:
          path: /home/ec2-user/demo-flask-ansible
        name: flask_quote_app
        tag: latest

    - name: Lancer le conteneur
      community.docker.docker_container:
        name: flask_quote_container
        image: flask_quote_app:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

    - name: Vérifier le conteneur
      shell: docker ps | grep flask_quote_container
      register: flask_container_status

    - name: Afficher le statut du conteneur
      debug:
        msg: "{{ flask_container_status.stdout }}"
