---
- name: Installer Docker et déployer Flask
  hosts: webservers
  become: true
  tasks:

    - name: Installer Docker
      yum:
        name: docker
        state: present

    - name: Démarrer et activer Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Ajouter ec2-user au groupe docker
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Copier le code Flask depuis Jenkins vers l'EC2
      copy:
        src: /var/lib/jenkins/workspace/demo-flask-ansible/
        dest: /home/ec2-user/flask_app/
        owner: ec2-user
        group: ec2-user
        mode: '0755'
        remote_src: no
        recurse: yes

    - name: Construire l'image Docker Flask
      community.docker.docker_image:
        source: build
        build:
          path: /home/ec2-user/flask_app
        name: flask_app
        tag: latest

    - name: Lancer le conteneur Flask
      community.docker.docker_container:
        name: flask_container
        image: flask_app:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

    - name: Vérifier que le conteneur tourne
      shell: docker ps | grep flask_container
      register: flask_container_status
      ignore_errors: yes

    - name: Afficher le statut du conteneur
      debug:
        msg: "{{ flask_container_status.stdout }}"
